// AUTO-GENERATED by scripts/build_sights_data.py — do not edit by hand.
// 人工补充的「看点 / 路边景色」默认数据，源 scripts/data/curated_sights.json。
// 非官方勘测，坐标为估算（WGS-84），仅供定位参考。
import type { Sight } from '../types'

export const DEFAULT_SIGHTS: Record<string, Sight[]> = {
  '01': [
    { id: "cur-01-1", name: "涉地可支 Seopjikoji", lng: 126.942, lat: 33.4554, type: "view", desc: "城山半岛北侧的火山岬角，草原、白色灯塔与油菜花田，是 1 号线（始兴→城山）沿线最著名的拍照点，紧邻城山日出峰。", images: [{"kind": "url", "value": "photos/sights/cur-01-1.webp", "width": 1280, "height": 720}] },
  ],
  '06': [
    { id: "cur-06-1", name: "正房瀑布 Jeongbang-pokpo", lng: 126.5617, lat: 33.2475, type: "water", desc: "济州三大瀑布之一，也是韩国唯一直接落入海中的瀑布；位于西归浦，6 号线（牛沼端→旅行者中心）终点附近。", images: [{"kind": "url", "value": "photos/sights/cur-06-1.webp", "width": 1280, "height": 853}] },
  ],
  '07': [
    { id: "cur-07-1", name: "天地渊瀑布 Cheonjiyeon-pokpo", lng: 126.5556, lat: 33.2494, type: "water", desc: "西归浦市区著名瀑布与亚热带溪谷步道，7 号线（旅行者中心→西归浦）起点一带。", images: [{"kind": "url", "value": "photos/sights/cur-07-1.webp", "width": 1280, "height": 960}] },
  ],
  '08': [
    { id: "cur-08-1", name: "柱状节理带 Daepo Jusangjeolli", lng: 126.428, lat: 33.237, type: "view", desc: "火山熔岩遇海水急速冷却形成的六棱柱状玄武岩海岸绝壁，8 号线（月坪→大坪）大浦一带的地标。", images: [{"kind": "url", "value": "photos/scenes/olle-08.webp", "width": 1600, "height": 1200}] },
  ],
  '14': [
    { id: "cur-14-1", name: "翰林公园 Hallim Park", lng: 126.267, lat: 33.398, type: "forest", desc: "集亚热带植物园、盆景园、溶洞（ 협재동굴/쌍용굴）于一体的综合公园，14 号线（低地→翰林）终点翰林一带。", images: [{"kind": "url", "value": "photos/sights/cur-14-1.webp", "width": 1280, "height": 853}] },
    { id: "cur-14-2", name: "飞扬岛 Biyang-do", lng: 126.258, lat: 33.415, type: "view", desc: "由翰林港乘船可达的离岛，火山地貌与环岛步道；14 号线终点翰林港正是前往飞扬岛的乘船点。", images: [{"kind": "url", "value": "photos/sights/cur-14-2.webp", "width": 1280, "height": 758}] },
  ],
  '15-A': [
    { id: "cur-15-A-1", name: "挟才海滩 Hyeopjae Beach", lng: 126.311, lat: 33.396, type: "view", desc: "济州西线最具代表性的白沙碧海海滩，与翰林公园相邻，15 号线（翰林→高内）途经。", images: [{"kind": "url", "value": "photos/scenes/olle-14.webp", "width": 1600, "height": 1071}] },
  ],
  '19': [
    { id: "cur-19-1", name: "咸德海水浴场 Hamdeok Beach", lng: 126.671945, lat: 33.544521, type: "view", desc: "济州东部最有名的海水浴场之一，白沙浅滩、水色清澈，紧邻犀牛峰；19 号线（朝天→金宁）6.3 km 处途经。", images: [{"kind": "url", "value": "photos/scenes/olle-18.webp", "width": 1600, "height": 1200}] },
    { id: "cur-19-2", name: "犀牛峰 Seowoo-bong", lng: 126.677494, lat: 33.550134, type: "view", desc: "咸德海边的小火山丘，登顶可俯瞰咸德海岸线，官方航点标注为 viewpoint（日落观赏点）；19 号线 7.4 km 处。", images: [] },
    { id: "cur-19-3", name: "4·3 纪念馆（너븐숭이） Neobeunsoongee April 3 Memorial", lng: 126.690399, lat: 33.548344, type: "ruin", desc: "犀牛峰一带 너븐숭이 的济州 4·3 事件纪念设施，官方航点标注为 viewpoint；19 号线 9.1 km 处。", images: [] },
    { id: "cur-19-4", name: "北村村落 Bukchon", lng: 126.695768, lat: 33.550758, type: "village", desc: "北村（북촌리）渔村与北村港一带，保留济州传统石墙与渔村风貌；19 号线 10.1 km 处途经。", images: [] },
  ],
  '20': [
    { id: "cur-20-1", name: "万丈窟 Manjanggul Cave", lng: 126.7716, lat: 33.5266, type: "view", desc: "联合国教科文世界自然遗产济州火山岛溶岩洞窟的一部分，长达数公里的熔岩隧道；位于 20 号线（金宁→下道）金宁一带。", images: [{"kind": "url", "value": "photos/sights/cur-20-1.webp", "width": 1280, "height": 720}] },
  ],
}
