#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
把人工补充的「看点 / 路边景色」源数据（scripts/data/curated_sights.json）生成为
TypeScript 模块 src/lib/sightsData.ts，导出 DEFAULT_SIGHTS: Record<code, Sight[]>。

为什么独立文件而不是写进 seed.ts：与途经点管线（build_waypoints_data.py → waypointsData.ts）
保持一致——可编辑的源放 scripts/data/，生成的 .ts 不手改。Sight 的坐标由源数据直接给出
（看点不吸附到轨迹线，是独立标注层），所以这里只是搬运 + 补 id / images 字段。

Sight 结构见 src/types.ts：
  interface Sight { id; name; lng; lat; type: SightType; desc?; images: ImageRef[] }
SightType = 'view' | 'water' | 'forest' | 'village' | 'ruin' | 'other'

输出：src/lib/sightsData.ts
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "data" / "curated_sights.json"
OUT = ROOT / "src" / "lib" / "sightsData.ts"

SIGHT_TYPES = {"view", "water", "forest", "village", "ruin", "other"}


def slug(name: str) -> str:
    # 仅取字母数字做 id 片段，避免韩文/中文进 id
    s = re.sub(r"[^A-Za-z0-9]+", "-", name).strip("-").lower()
    return s or "sight"


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    sights = data["sights"]
    if not isinstance(sights, dict):
        raise SystemExit("curated_sights.json: 'sights' 必须是按路线 code 分组的对象")

    result: dict[str, list[dict]] = {}
    for code, items in sights.items():
        out_items = []
        for i, s in enumerate(items, 1):
            t = s.get("type", "other")
            if t not in SIGHT_TYPES:
                raise SystemExit(f"{code}: 未知 SightType '{t}'")
            imgs = s.get("images") or []
            if not isinstance(imgs, list):
                imgs = []
            out_items.append({
                "id": f"cur-{code}-{i}",
                "name": s["name"],
                "lng": round(float(s["lng"]), 6),
                "lat": round(float(s["lat"]), 6),
                "type": t,
                "desc": s.get("desc", ""),
                "images": imgs,
            })
        result[code] = out_items

    lines = [
        "// AUTO-GENERATED by scripts/build_sights_data.py — do not edit by hand.",
        "// 人工补充的「看点 / 路边景色」默认数据，源 scripts/data/curated_sights.json。",
        "// 非官方勘测，坐标为估算（WGS-84），仅供定位参考。",
        "import type { Sight } from '../types'",
        "",
        "export const DEFAULT_SIGHTS: Record<string, Sight[]> = {",
    ]
    for code in sorted(result.keys()):
        lines.append(f"  '{code}': [")
        for s in result[code]:
            desc = json.dumps(s["desc"], ensure_ascii=False)
            imgs = json.dumps(s["images"], ensure_ascii=False)
            lines.append(
                f"    {{ id: {json.dumps(s['id'])}, name: {json.dumps(s['name'], ensure_ascii=False)}, "
                f"lng: {s['lng']}, lat: {s['lat']}, type: {json.dumps(s['type'])}, "
                f"desc: {desc}, images: {imgs} }},"
            )
        lines.append("  ],")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    total = sum(len(v) for v in result.values())
    print(f"Wrote {OUT}")
    print(f"routes with curated sights: {len(result)} | total sights: {total}")
    for code in sorted(result.keys()):
        print(f"  {code}: {len(result[code])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
